[build]
  publish = "public"
  command = "hugo --minify --gc"
t 
[build.environment]
  HUGO_VERSION = "0.108.0"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.