
name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:

 hugo-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.91.2
          TARGET_REPO: stiliajohny/stiliajohny.github.io
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.HUGO_TOKEN }}
          HUGO_EXTENDED: true
          # HUGO_ARGS: '-t academic'
          # CNAME: benmatselby.github.io

 sitemap-ping:
    name: Google Sitemap Ping
    needs: hugo-deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: ping
        env:
          MAP_URL: "NULL" # set custom URL if you use it
        run: |
          BASE_URL="https://stiliajohny.github.io"
          MAP_URL="${BASE_URL}/sitemap.xml"
          RSS_URL="${BASE_URL}/index.xml"
          sleep 3
          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
          wait
          echo "Done"

 publish:
    runs-on: ubuntu-latest
    needs: sitemap-ping
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
