
name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:

 hugo-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.91.2
          TARGET_REPO: stiliajohny/stiliajohny.github.io
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.HUGO_TOKEN }}
          HUGO_EXTENDED: true
          # HUGO_ARGS: '-t academic'
          # CNAME: benmatselby.github.io

 sitemap-ping:
    name: Google Sitemap Ping
    needs: hugo-deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: ping
        env:
          MAP_URL: "NULL" # set custom URL if you use it
        run: |
          BASE_URL="https://stiliajohny.github.io"
          MAP_URL="${BASE_URL}/sitemap.xml"
          RSS_URL="${BASE_URL}/index.xml"
          sleep 3
          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
          wait
          echo "Done"

 publish:
    runs-on: ubuntu-latest
    needs: sitemap-ping
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Publish articles on dev.to
      uses: sinedied/publish-devto@v2
      with:
        # Your dev.to personal API key to publish and update articles.
        # See https://docs.dev.to/api/#section/Authentication/api_key
        devto_key: ${{ secrets.DEVTO_TOKEN }}
        # Your GitHub personal access token, used to create commits for updated files.
        # If you have a protected branch, you need to use a personal access token
        # with the 'repo' permission.
        # See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # (Optional) The files to publish. Default is "posts/**/*.md"
        files: 'content/posts/**/*.md'
        # (Optional) The git branch to use. Default is 'main'.
        branch: master
        # (Optional) Use conventional commit messages. Default is false.
        # See https://www.conventionalcommits.org.
        conventional_commits: true
      env:
        GIT_COMMITTER_NAME: John Stilia
        GIT_COMMITTER_EMAIL: stilia.johny+gh_actions@gmail.com