---
name: Build Blog
on:
  push:
    branches:
      - master

jobs:
  hugo-build:
    name: Install hugo and build site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install Hugo
        run: |
          sudo apt update
          sudo apt install wget -y
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.108.0/hugo_extended_0.108.0_Linux-64bit.tar.gz
          tar -xzf hugo_extended_0.108.0_Linux-64bit.tar.gz
          mv hugo /usr/local/bin
          hugo version
          # build the site targeting the gh-pages branch
          hugo -v --cleanDestinationDir --destination=public --baseURL=https://indraft.blog --config=config.toml

      - name: Temporarily save the site
        uses: actions/upload-artifact@v2
        with:
          name: hugo-site
          path: public
          retention-days: 1

  commit_gh_pages:
    name: Commit to gh-pages
    runs-on: ubuntu-20.04
    needs: hugo-build
    steps:
      - name: Download the siten from the previous step
        #  ignore failure

        uses: actions/download-artifact@v2
        with:
          name: hugo-site
          path: public

      - name: Commit to gh-pages
        run: |
          # Set up git
          git config --global user.name "stiliajohny"
          git config --global user.email "stilia.john@gmail.com"
          cd public
          git init
          git add .
          git commit -m "Deploy main commit ${GITHUB_SHA} to gh-pages branch"
          git push --force --quiet "https://${{ secrets.HUGO_TOKEN }}@github.com/stiliajohny/stiliajohny.github.io" master:gh-pages

      # delete-artifact
      - uses: geekyeggo/delete-artifact@v2
        with:
            name: hugo-site

  sitemap-ping:
    name: Google Sitemap Ping
    needs: commit_gh_pages
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: ping
        env:
          MAP_URL: "NULL" # set custom URL if you use it
        run: |
          BASE_URL="https://indraft.blog"
          MAP_URL="${BASE_URL}/sitemap.xml"
          RSS_URL="${BASE_URL}/index.xml"
          sleep 3
          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
          wait
          echo "Done"

  create-nojekyll:
    name: File .nojekyll
    needs: sitemap-ping
    runs-on: ubuntu-latest
    steps:
      - name: Create .nojekyll file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".nojekyll"
          FILE_DATA: ""

  slack-notification:
    runs-on: ubuntu-latest
    name: Slack Notification
    needs: create-nojekyll

    steps:
      # Set up the Slack action
      - uses: actions/setup-slack-action@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
      # Send the message to the Slack channel
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}