---
name: Build Blog
on:
  push:
    branches:
      - master

jobs:
  hugo-build:
    name: Install hugo and build site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install Hugo
        run: |
          sudo apt update
          sudo apt install wget -y
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.108.0/hugo_extended_0.108.0_Linux-64bit.tar.gz
          tar -xzf hugo_extended_0.108.0_Linux-64bit.tar.gz
          mv hugo /usr/local/bin
          hugo version
          # build the site targeting the gh-pages branch
          hugo -v --cleanDestinationDir --destination=public --baseURL=https://indraft.blog --config=config.toml

      - name: Temporarily save the site
        uses: actions/upload-artifact@v2
        with:
          name: hugo-site
          path: public
          retention-days: 1

  commit_gh_pages:
    name: Commit to gh-pages
    runs-on: ubuntu-20.04
    needs: hugo-build
    steps:
      - name: Download the siten from the previous step
        uses: actions/download-artifact@v2
        with:
          name: hugo-site
          path: public

      # Create the gh-pages branch if it doesn't exist
      - run: git branch --orphan gh-pages
      # Checkout the gh-pages branch
      - run: git checkout gh-pages
      # Remove all existing files from the branch
      - run: git rm -rf .
      # Add the contents of the folder to the staging area
      - run: git add public/*
      # Commit the changes with a message
      - run: git commit -m "Committing folder to gh-pages branch"
      # Push the changes to the gh-pages branch
      - run: git push origin gh-pages

      # delete-artifact
      - uses: geekyeggo/delete-artifact@v2
        with:
            name: hugo-site


  #     - name: Deploy the site
  #       uses: benmatselby/hugo-deploy-gh-pages@main
  #       env:
  #         HUGO_VERSION: 0.91.2
  #         TARGET_REPO: stiliajohny/stiliajohny.github.io
  #         TARGET_BRANCH: gh-pages
  #         TOKEN: ${{ secrets.HUGO_TOKEN }}
  #         HUGO_EXTENDED: true
  #         # HUGO_ARGS: '-t academic'
  #         CNAME: indraft.blog

  # sitemap-ping:
  #   name: Google Sitemap Ping
  #   needs: hugo-deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Checkout Repository"
  #       uses: actions/checkout@v2
  #     - name: ping
  #       env:
  #         MAP_URL: "NULL" # set custom URL if you use it
  #       run: |
  #         BASE_URL="https://indraft.blog"
  #         MAP_URL="${BASE_URL}/sitemap.xml"
  #         RSS_URL="${BASE_URL}/index.xml"
  #         sleep 3
  #         curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
  #         curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
  #         curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
  #         curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
  #         wait
  #         echo "Done"

  # create-nojekyll:
  #   name: File .nojekyll
  #   needs: sitemap-ping
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create .nojekyll file
  #       uses: "finnp/create-file-action@master"
  #       env:
  #         FILE_NAME: ".nojekyll"
  #         FILE_DATA: ""
