name: Check for merge conflicts
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  build:
    name: potential-conflicts-checker
    runs-on: ubuntu-latest
    steps:
      - uses: outsideris/potential-conflicts-checker-action@0.1.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
